language: cpp
compiler: gcc
dist: xenial

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++17
  - sudo apt-get install -qq g++-8
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq libboost-test-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

script:
  - mkdir build && cd build
  - cmake ..
  - cmake
  - ctest
